### ISSUE TITLE
How do i add or remove environments from the pipeline

### ISSUE THREAD

**Issue by TraGicCode** [akamai/cli-property-manager#2]
Is there a way to easily add or remove environment from the pipeline manually?  Could this be documented? Could VNext possibly have this added as 2 sub commands:

1. akamai promotional-deployment remove-environment
1. akamai promotional-deployment add-environment

**Comment by jumenzel** [comment]
Great idea. I think there are a few possibilities and corner cases to consider. 
### Add scenario:
- what position should the environment be added. We could use options -a <envname> for after or -b <envname> for before environment. 
- Akamai pd would just create the environment property as if it was running the new pipeline command
- After insertion of the new environment all promotions on environments after that would be blocked until the new environment has been promoted. 
### Remove scenario
- Just remove the environment name from the list in projectInfo.json. 
- Delete environment folder or move it into an archive folder.
- What about the environment property? It would just continue to exist outside of the pipeline.

**Comment by TraGicCode** [comment]
Is there a manual workaround for this at the moment?

/cc @jumenzel

**Comment by jumenzel** [comment]
There is one. It's not very straight forward. It goes roughly like this:
- In Property Manager UI look for one of the properties of your pipeline. Let's say "qa.pipeline"
- Clone this property and give it a name corresponding to the new environment you want to add, for example "dev.pipeline".
- Once done click on save to save the cloned property (this might not even be necessary)
- in Akamai PD, search for the new property: akamai pd search dev.pipeline
- Deep copy on of the environment folder to a new folder with the name of the new environment.
(in environemnts do a "cp -a qa dev" for example)
- Add the new environment name to the list in projectInfo.json 
- Edit hostnames.json file. If you also change the edgehostnames set the ids to null so that Akamai PD creates new edgehostnames. 
- In the new environment folder edit envInfo.json and remove all the keys except for 'name', 'propertyName', 'propertyId', 'latestVersionInfo', 'suggestedRuleFormat', 'groupId'. 
- Edit the values name = 'dev', propertyName = 'dev.pipeline', propertyId = 'property Id from search'
- Edit latestVersionInfo, set version to 1. Set both networks to INACTIVE. 
- Now try to save: akamai pd -v save dev
- This should blow up with a etag exception. Luckily the correct etag value shows up in the error message. Replace with the wrong etag in latestVersionInfo.
- Try save again. This time it should work.
I only tried adding a new environment by adding it to the front of the pipeline. I think the same mechanism should  work for any position in the pipeline.
