### ISSUE TITLE
refresh envInfo.json

### ISSUE THREAD

**Issue by optplx** [akamai/cli-property-manager#37]
Hi all,

it would be nice to have a command to refresh or regenerate the envInfo.json file, this could avoid the need to commit it. Indeed, as I have a distributed team, I would rather regenerate this file every time from my centralized jenkins rather than trusting the commiters about it.

what do you think?
thanks!

**Comment by optplx** [comment]
up, any news regarding this idea? is it doable? 

as of now I do the following workaround (quick and dirty): run the akamai property-manager import command, and and copy/paste the "newly generated" envInfo.json file, but this is not really smooth...

but still, it looks like the code is already here since the job is done during the import

thanks!

**Comment by aarondotsteele** [comment]
+1 for this feature. There are a few scenarios in our workflow where these can get out of sync and it would be incredibly beneficial to have a command for this instead of doing what @optplx describes.

**Comment by zstlaw** [comment]
While we do not have a regenerate EnvInfo file command what we did in 0.6 version was remove the logic which was the root cause of most of the conflicts in federated development.  

With the change to our EnvInfo logic most of the issues with out of date EnvInfo.json should go away.  If you still have problems after 0.6 comes much of that logic becomes centralized in the next version tentatively named 1.0 and already well under development.

**Comment by NehaGhateAkamai** [comment]
The other way to refresh envInfo.json is save and merge command. This updates the envInfo.json.
Usage: save|sv [options] <environment>
Usage: merge|m [options] <environment>
 This updates the envInfo.json.
