### ISSUE TITLE
Add 'push' command

### ISSUE THREAD

**Issue by ddcrjlalumiere** [akamai/cli-property-manager#42]
Ideally one would be able to push an updated configuration version without having to 'activate' it on either network.

**Comment by zstlaw** [comment]
This should be possible already.  But in practice it is a bit different for pipeline vs snippets.

The save operation does this but it validates the property first. This might have been confusing because if the current version was already "active" in staging or production a new version must be created as part of save action since already active versions are not editable.

Usage: 
`    pipeline save -p <pipeline_name> <environment>`
        or
`    snippets save`

either operation will push the local change without doing an activation.
